In [86]:
# データ加工・処理・分析ライブラリ
import numpy as np
import numpy.random as random
import scipy as sp
from pandas import Series, DataFrame
import pandas as pd

# 可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 機械学習ライブラリ
import sklearn

# 小数第3位まで表示
%precision 3

'%.3f'

In [87]:
#データの読み込み
df = pd.read_csv("enc_vital_2.csv")
df

,Unnamed: 0,Encounter_ID,age,sex,Disposition,VS_date,VS_time,VS_timing,Cons_JCS,SBP,DBP,PR,RR,BT
0,0,K1JER10000,67.0,男,入院,2020-09-25,12:46:12,病着時,0.0,106.0,62.0,117.0,10.0,40.4
1,2,K1JER10001,77.0,男,帰宅,2020-08-22,15:46:59,病着時,0.0,157.0,72.0,125.0,18.0,NaN
2,4,K1JER10003,44.0,男,入院,2020-08-22,16:22:51,病着時,0.0,149.0,99.0,76.0,NaN,NaN
3,6,K1JER10009,92.0,男,入院,2020-09-25,12:58:43,病着時,0.0,143.0,81.0,66.0,14.0,36.2
4,8,K1JER10010,76.0,男,帰宅,2020-08-22,19:48:34,病着時,0.0,136.0,90.0,67.0,15.0,36.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11999,20819,KCHER9994,66.0,男,キャンセル,2020-08-25,10:32:46,病着時,NaN,180.0,80.0,90.0,20.0,37.0
12000,20820,KCHER9995,60.0,男,入院,2020-08-21,18:51:09,病着時,2.0,167.0,101.0,88.0,19.0,37.3
12001,20821,KCHER9996,78.0,男,帰宅,2020-08-21,13:34:35,病着時,0.0,165.0,97.0,74.0,20.0,36.8
12002,20822,KCHER9997,53.0,男,死亡,2020-08-21,15:56:23,病着時,300.0,NaN,NaN,135.0,NaN,39.8
12003,20823,KCHER9999,46.0,男,帰宅,2020-08-21,16:51:33,病着時,0.0,128.0,78.0,57.0,13.0,36.5

In [88]:
# 欠損数を出力
df.isnull().sum()

Unnamed: 0         0
Encounter_ID       0
age                0
sex                1
Disposition      115
VS_date            0
VS_time            0
VS_timing          0
Cons_JCS        1329
SBP              596
DBP              654
PR               681
RR              1914
BT              1131
dtype: int64

In [89]:
#sex,Dispositionが欠損の行は削除
#dropnaはinplace=Trueにしないと元のデータに変更が反映されない
df.dropna(subset=['sex','Disposition'], inplace=True)
df

,Unnamed: 0,Encounter_ID,age,sex,Disposition,VS_date,VS_time,VS_timing,Cons_JCS,SBP,DBP,PR,RR,BT
0,0,K1JER10000,67.0,男,入院,2020-09-25,12:46:12,病着時,0.0,106.0,62.0,117.0,10.0,40.4
1,2,K1JER10001,77.0,男,帰宅,2020-08-22,15:46:59,病着時,0.0,157.0,72.0,125.0,18.0,NaN
2,4,K1JER10003,44.0,男,入院,2020-08-22,16:22:51,病着時,0.0,149.0,99.0,76.0,NaN,NaN
3,6,K1JER10009,92.0,男,入院,2020-09-25,12:58:43,病着時,0.0,143.0,81.0,66.0,14.0,36.2
4,8,K1JER10010,76.0,男,帰宅,2020-08-22,19:48:34,病着時,0.0,136.0,90.0,67.0,15.0,36.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11999,20819,KCHER9994,66.0,男,キャンセル,2020-08-25,10:32:46,病着時,NaN,180.0,80.0,90.0,20.0,37.0
12000,20820,KCHER9995,60.0,男,入院,2020-08-21,18:51:09,病着時,2.0,167.0,101.0,88.0,19.0,37.3
12001,20821,KCHER9996,78.0,男,帰宅,2020-08-21,13:34:35,病着時,0.0,165.0,97.0,74.0,20.0,36.8
12002,20822,KCHER9997,53.0,男,死亡,2020-08-21,15:56:23,病着時,300.0,NaN,NaN,135.0,NaN,39.8
12003,20823,KCHER9999,46.0,男,帰宅,2020-08-21,16:51:33,病着時,0.0,128.0,78.0,57.0,13.0,36.5

In [90]:
# 欠損数を出力
df.isnull().sum()

Unnamed: 0         0
Encounter_ID       0
age                0
sex                0
Disposition        0
VS_date            0
VS_time            0
VS_timing          0
Cons_JCS        1319
SBP              583
DBP              641
PR               666
RR              1887
BT              1108
dtype: int64

In [91]:
#Dispositionの要素
set(df.Disposition.values)

{'キャンセル', '一般外来紹介', '一般外来紹介帰宅', '入院', '帰宅', '来院せず', '死亡', '直接入院', '転院'}

In [92]:
#Dispositionがキャンセル、来院せず、死亡の行を削除
df = df[df['Disposition'] != 'キャンセル']
df = df[df['Disposition'] != '来院せず']
df = df[df['Disposition'] != '死亡']
df

,Unnamed: 0,Encounter_ID,age,sex,Disposition,VS_date,VS_time,VS_timing,Cons_JCS,SBP,DBP,PR,RR,BT
0,0,K1JER10000,67.0,男,入院,2020-09-25,12:46:12,病着時,0.0,106.0,62.0,117.0,10.0,40.4
1,2,K1JER10001,77.0,男,帰宅,2020-08-22,15:46:59,病着時,0.0,157.0,72.0,125.0,18.0,NaN
2,4,K1JER10003,44.0,男,入院,2020-08-22,16:22:51,病着時,0.0,149.0,99.0,76.0,NaN,NaN
3,6,K1JER10009,92.0,男,入院,2020-09-25,12:58:43,病着時,0.0,143.0,81.0,66.0,14.0,36.2
4,8,K1JER10010,76.0,男,帰宅,2020-08-22,19:48:34,病着時,0.0,136.0,90.0,67.0,15.0,36.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11997,20817,KCHER9991,85.0,男,入院,2020-08-21,11:53:35,病着時,0.0,137.0,64.0,100.0,33.0,36.7
11998,20818,KCHER9993,43.0,男,帰宅,2020-08-21,13:33:09,病着時,0.0,116.0,77.0,74.0,11.0,37.0
12000,20820,KCHER9995,60.0,男,入院,2020-08-21,18:51:09,病着時,2.0,167.0,101.0,88.0,19.0,37.3
12001,20821,KCHER9996,78.0,男,帰宅,2020-08-21,13:34:35,病着時,0.0,165.0,97.0,74.0,20.0,36.8
12003,20823,KCHER9999,46.0,男,帰宅,2020-08-21,16:51:33,病着時,0.0,128.0,78.0,57.0,13.0,36.5

In [93]:
#性別の数値変換
df.loc[(df['sex'] == '男'), 'sex'] = 0
df.loc[(df['sex'] == '女'), 'sex'] = 1

#Dispositionの数値変換
df['Disposition'] = df['Disposition'].replace({'入院':'0', '直接入院':'0', '転院':'0', '一般外来紹介':'1','一般外来紹介帰宅':'1','帰宅':'1'})
df

,Unnamed: 0,Encounter_ID,age,sex,Disposition,VS_date,VS_time,VS_timing,Cons_JCS,SBP,DBP,PR,RR,BT
0,0,K1JER10000,67.0,0,0,2020-09-25,12:46:12,病着時,0.0,106.0,62.0,117.0,10.0,40.4
1,2,K1JER10001,77.0,0,1,2020-08-22,15:46:59,病着時,0.0,157.0,72.0,125.0,18.0,NaN
2,4,K1JER10003,44.0,0,0,2020-08-22,16:22:51,病着時,0.0,149.0,99.0,76.0,NaN,NaN
3,6,K1JER10009,92.0,0,0,2020-09-25,12:58:43,病着時,0.0,143.0,81.0,66.0,14.0,36.2
4,8,K1JER10010,76.0,0,1,2020-08-22,19:48:34,病着時,0.0,136.0,90.0,67.0,15.0,36.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11997,20817,KCHER9991,85.0,0,0,2020-08-21,11:53:35,病着時,0.0,137.0,64.0,100.0,33.0,36.7
11998,20818,KCHER9993,43.0,0,1,2020-08-21,13:33:09,病着時,0.0,116.0,77.0,74.0,11.0,37.0
12000,20820,KCHER9995,60.0,0,0,2020-08-21,18:51:09,病着時,2.0,167.0,101.0,88.0,19.0,37.3
12001,20821,KCHER9996,78.0,0,1,2020-08-21,13:34:35,病着時,0.0,165.0,97.0,74.0,20.0,36.8
12003,20823,KCHER9999,46.0,0,1,2020-08-21,16:51:33,病着時,0.0,128.0,78.0,57.0,13.0,36.5

In [94]:
#欠損値補完
df.fillna(df.mean(),inplace=True)

In [95]:
# 欠損数を出力
df.isnull().sum()

Unnamed: 0      0
Encounter_ID    0
age             0
sex             0
Disposition     0
VS_date         0
VS_time         0
VS_timing       0
Cons_JCS        0
SBP             0
DBP             0
PR              0
RR              0
BT              0
dtype: int64

In [116]:
#ロジスティック回帰で分類
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split,cross_val_score

# 標準化のためのクラスをインポート
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# 説明変数と目的変数の設定
X = df[['age', 'sex', 'Cons_JCS', 'SBP', 'DBP','PR','RR','BT']]
y = df['Disposition']

# 訓練データとテストデータに分ける
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

# 標準化処理
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

cls = LogisticRegression(max_iter=10000)

#4分割で交差検証を行う
score = cross_val_score(cls, X_train, y_train, cv=4)

print("交差検証の結果")
print(score)
print("交差検証の平均")
print("{:.3f}".format(np.mean(score)))

#訓練～テスト
cls.fit(X_train,y_train)

print("テストデータの評価")
print("{:.3f}".format(cls.score(X_test, y_test)))

交差検証の結果
[0.628 0.655 0.639 0.646]
交差検証の平均
0.642
テストデータの評価
0.654

In [117]:
#各変数の係数を確認
model.coef_

array([[-2.623e-02,  3.177e-01, -8.367e-03, -2.028e-05,  4.082e-04,
         5.077e-05, -1.517e-02,  5.470e-02]])